"""Add distance column

Revision ID: e5ac6c018a7f
Revises: 
Create Date: 2024-12-03 03:51:28.639327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ac6c018a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_mode', sa.String(length=2), nullable=True),
    sa.Column('beam_mode', sa.String(length=2), nullable=True),
    sa.Column('machine_mode', sa.String(length=2), nullable=True),
    sa.Column('ion_type', sa.String(length=50), nullable=True),
    sa.Column('charge_state', sa.Integer(), nullable=True),
    sa.Column('beam_energy', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pv_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('set_pv_name', sa.String(length=100), nullable=False),
    sa.Column('set_value', sa.Float(), nullable=False),
    sa.Column('readback_pv_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('HH', sa.Float(), nullable=True),
    sa.Column('High', sa.Float(), nullable=True),
    sa.Column('Low', sa.Float(), nullable=True),
    sa.Column('LL', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pv_dataset')
    op.drop_table('experiment')
    # ### end Alembic commands ###
